export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  READY_IN_STORE = 'READY_IN_STORE',
  DELIVERY_TO_STATION = 'DELIVERY_TO_STATION',
  DELIVERY_IN_PROGRESS = 'DELIVERY_IN_PROGRESS',
  AVAILABLE_AT_COUNTER = 'AVAILABLE_AT_COUNTER',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
export enum DeliveryMethod {
  STANDARD = 'STANDARD',
  EXPRESS = 'EXPRESS',
  PICKUP = 'PICKUP',
}

export enum PaymentMethod {
  MOBILE_MONEY = 'MOBILE_MONEY',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
}

export enum CartStatus {
  ACTIVE = 'ACTIVE',
  CONVERTED = 'CONVERTED',
  ABANDONED = 'ABANDONED',
}
